# Generated by Django 2.2 on 2020-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'List Item'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'List'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statuse'},
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
