# Generated by Django 2.2 on 2020-10-03 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201003_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 3, 18, 4, 21, 630882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 10, 3, 18, 4, 33, 525937, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 3, 18, 4, 42, 948175, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
