# Generated by Django 2.2 on 2020-12-01 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201006_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
